=encoding UTF8

=head1 NAME

rofi-man - rofi-script to search for executables by their name or functionality

=head1 SYNOPSIS

rofi-man [B<--help>] [B<--test>] [file] [B<section>]

B<file> is any executable available that has a man page.

=head1 DESCRIPTION

B<rofi-man> is best used with B<rofi> as a B<rofi-script>. The simple idea behind this is that it natural to search for executables by either their names(if they're named appropriately) OR from their advertised functionality in their short descriptions.

=head1 OPTIONS

=over

=item B<-h>

Show the help section on how to use `rofi-man`

=item B<-t>

Returns the `man` compliant argument given to this script. Important for testing.

=back

=head1 EXAMPLES

=over

=item B<use-with-i3>

bindsym $mod+m exec --no-startup-id rofi -show man -modes "man:rofi-man" -matching regex -tokenize

=item B<use-in-shell>

rofi -show man -modes "man:rofi-man" -matching regex -tokenize

=back

=head1 PREREQUISITES

=over

=item * B<rofi> needed to work albiet the script on it's own I<can be used> but I<may not be useful>.

=item * B<whatis>

=item * B<man>

=item * terminal emulator like B<kitty>, B<konsole>, B<urxvt>...

=back

=head1 SEE ALSO

B<whatis(1)>, B<apropos(1)>, B<man(1)>, B<rofi(1)>, B<rofi-script(5)>

=head1 AUTHOR

Neel Maitra <OPhamster@users.noreply.github.com>
